config/routes.rb
Glvote::Application.routes.draw do
  root :to => 'home#index'

  resource :login, :only => [:new, :create, :destroy], :controller => 'login'

  resources :booths, :only => [:show, :update] do
    resource :connection, :only => [:create, :destroy], :controller => 'booth_connections'
    member do
      post 'reset'
    end
  end

  resources :voter_registrations, :only => [:create]

end

app/models/ballot.rb
class Ballot < ActiveRecord::Base
  has_many :selections, :class_name => 'BallotSelection'
end

app/models/ballot_selection.rb
class BallotSelection < ActiveRecord::Base
  belongs_to :ballot
  belongs_to :candidate
  has_one    :office, :through => :candidate
end

app/models/booth.rb
class Booth < ActiveRecord::Base
  belongs_to :active_ballot, :class_name => 'Ballot'
  belongs_to :active_office, :class_name => 'Office'

  default_scope :order => :id

  def active_selection
    existing_active_selection = self.active_ballot.selections.joins(:candidate).where("candidates.office_id" => self.active_office.id).first
    existing_active_selection || self.active_ballot.selections.new
  end

  def active_selection_attributes=(attributes)
    if self.active_selection.new_record?
      writable_active_selection = self.active_selection
    else
      writable_active_selection = BallotSelection.find(self.active_selection.id)
    end
    writable_active_selection.update_attributes(attributes)
  end

  def activate!(voter_name)
    self.voter_name = voter_name
    self.active_ballot = Ballot.new
    self.active_office = Office.first
    self.state = ReadyState
    save!
  end

  def deactivate!
    self.voter_name = nil
    self.active_office = nil
    self.active_ballot = nil
    self.state = InactiveState
    save!
  end

  def booth_connection
    BoothConnection.new(booth_id: self.id)
  end

  def state
    @state ||= self.state_name.camelize.constantize.new(self)
  end

  def state=(value)
    @state = nil
    if value.class == Class
      self.state_name = value.to_s.underscore
    else
      self.state_name = value.class.to_s.underscore
    end
    FayeNotifier.publish('/booths',
                         id: self.id,
                         voter_name: self.voter_name,
                         human_status: self.state.human_status,
                         css_class: self.state.css_class)
  end
end

app/models/booth_connection.rb
class BoothConnection
  extend  ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :booth_id

  def initialize(params = {})
    self.booth_id = params[:booth_id]
  end

  def id
    nil
  end

  def persisted?
    false
  end
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  has_many :ballot_selections

  def photo_url
    "/candidates/#{self.id}.jpg"
  end
end

app/models/faye_notifier.rb
class FayeNotifier
  def self.publish(channel, params)
    require 'net/http'
    message = { channel: channel, data: params }
    uri = URI.parse(Rails.configuration.faye_url)
    Net::HTTP.post_form(uri, :message => message.to_json)
  end
end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :candidates
end

app/models/voter_registration.rb
class VoterRegistration
  extend  ActiveModel::Naming
  include ActiveModel::Conversion

  attr_accessor :booth_id, :voter_name

  def initialize(params = {})
    self.booth_id   = params[:booth_id]
    self.voter_name = params[:voter_name]
  end

  def id
    nil
  end

  def persisted?
    false
  end

  def save
    Booth.find(self.booth_id).activate!(self.voter_name)
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  ELECTION_WORKER = 1

  helper_method :logged_in?
  def logged_in?
    session[:role].present?
  end

  def redirect_to_login
    session[:pre_auth_url] = request.fullpath
    redirect_to new_login_url
  end
end

app/controllers/booth_connections_controller.rb
class BoothConnectionsController < ApplicationController
  def create
    if logged_in? && session[:role] == ELECTION_WORKER
      booth_id = params[:booth_id].to_i
      session[:booth_id] = booth_id
      redirect_to booth_url(booth_id)
    else
      session[:booth_id] = nil
      redirect_to_login
    end
  end
end

app/controllers/booths_controller.rb
class BoothsController < ApplicationController
  layout 'booths'

  def show
    @booth = Booth.find(params[:id])
    render @booth.state.view_name
  end

  def update
    @booth = Booth.find(params[:id])
    @booth.update_attributes!(params[:booth])
    submit = params[:commit]
    # If a submit parameter was passed try to call it on our current state
    if submit.present?
      submit = submit.gsub(' ','').underscore.to_sym
      if @booth.state.respond_to?(submit)
        # If the method accepts an argument pass in self
        if @booth.state.method(submit).arity == 1
          @booth.state.send(submit, self)
        else
          @booth.state.send(submit)
        end
        @booth.save!
      end
    end
    # If the state didn't trigger any rendering then default to render the state's view_name
    if response_body.nil?
      if request.xhr?
        render @booth.state.view_name, layout: false
      else
        render @booth.state.view_name
      end
    end
  end

  # Resets a booth. This happens when a poll worker needs to reverse an activation.
  def reset
    if logged_in?
      booth = Booth.find(params[:id])
      booth.deactivate!
      redirect_to root_url
    else
      redirect_to_login
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      @booths = Booth.all
      @registration = VoterRegistration.new
    else
      redirect_to_login
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    if params[:login][:password] == Rails.configuration.election_worker_password
      session[:role] = ELECTION_WORKER
      redirect_to session[:pre_auth_url]
    else
      session[:role] = nil
      flash.now[:notice] = 'Unable to login, check that you have permission and the correct password.'
      render 'new'
    end
  end

  def destroy
    session[:role] = nil
    redirect_to root_url, notice: 'You have been logged out.'
  end
end

app/controllers/voter_registrations_controller.rb
class VoterRegistrationsController < ApplicationController
  def create
    if logged_in?
      registration = VoterRegistration.new(params[:voter_registration])
      if registration.save
        redirect_to root_url
      else
        redirect_to root_url, notice: 'An error occurred registering the voter.'
      end
    else
      redirect_to_login
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/booths/ballot_confirmation.html.erb
<div class="page-header">
  <h1>Confirmation</h1>
</div>
<%= form_for @booth, remote: true do |f| %>
  <div class="input">
    <p>You are about to cast your ballot.</p>
  </div>
  <div class="actions">
    <%= f.submit 'Cast Ballot', :class => 'btn primary large pull-right' %>
    <%= f.submit 'Previous', :class => 'btn large' %>
  </div>
<% end %>

app/views/booths/ballot_instructions.html.erb
<%= form_for @booth, remote: true do |f| %>
  <div class="page-header">
    <h1>Instructions</h1>
  </div>
  <div class="well">
    After pressing the Next button you will begin voting. Each office will be displayed one at a time
    along with a list of candidates. Make your selection by pressing the candidates picture or name.
    The candidate you select will be become highlighted to indicate which selection you made. Press
    Next to few the next available office or Previous to go back if you wish to change a selection.
  </div>
  <%= f.hidden_field :instructions_confirmed, :value => true %>
  <%= f.submit 'Next', :class => 'btn primary large pull-right' %>
<% end %>

app/views/booths/ballot_selection.html.erb
<%= form_for @booth, remote: true do |f| %>
  <div class="page-header">
    <h1><%= @booth.active_office.name %></h1>
  </div>
  <div class="well">
    <div class="candidates">
      <%= f.fields_for :active_selection do |active_selection_fields| %>
        <% @booth.active_office.candidates.each do |candidate| %>
          <div class="candidate alert-message <%= 'success' if candidate.id == @booth.active_selection.candidate_id %>">
            <label>
              <img src="<%= candidate.photo_url %>">
              <%= active_selection_fields.radio_button :candidate_id, candidate.id %>
              <%= candidate.name %>
            </label>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= f.submit 'Next', :class => 'btn primary large pull-right' %>
  <%= f.submit 'Previous', :class => 'btn large' %>
<% end %>

app/views/booths/inactive.html.erb
<div class="page-header">
  <h1>Please wait for a poll worker to activate this voting booth.</h1>
</div>
<%= form_for @booth, remote: true do |f| %>
  <div class="input">
  </div>
  <div class="actions">
  </div>
<% end %>

app/views/booths/ready.html.erb
<h1>Ready</h1>
<%= form_for @booth, remote: true do |f| %>
  Press begin to start voting.
  <%= f.hidden_field :begin_pressed, :value => true %>
  <%= f.submit 'Begin', :class => 'btn primary large' %>
<% end %>

app/views/booths/voter_confirmation.html.erb
<%= form_for @booth, remote: true do |f| %>
  <div class="page-header">
    <h1>Voter Confirmation</h1>
  </div>
  <div class="well">
    Is your name <%= @booth.voter_name %>?
  </div>
  <%= f.hidden_field :voter_name_confirmed, :value => true %>
  <%= f.submit 'Yes', :class => 'btn primary large pull-right' %>
  <%= f.submit 'No', :class => 'btn large' %>
<% end %>

app/views/home/_voter_registration.html.erb
<%= form_for @registration do |f| %>
  <fieldset>
    <legend>
      Voter Registration
    </legend>
    <div class="clearfix">
      <%= f.label :voter_name %>
      <div class="input">
        <%= f.text_field :voter_name %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :booth_id %>
      <div class="input">
        <%= f.select :booth_id, Booth.all.collect {|b| ["Voting Booth ##{b.id}", b.id] } %>
      </div>
    </div>
    <div class="clearfix">
      <div class="input">
        <%= f.submit 'Register Voter', class: 'btn primary', disable_with: 'Loading...' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/home/index.html.erb
<% content_for :javascript do %>
  $(function() {
    window.worker_view = new GLVote.WorkerView({faye_url: '<%= Rails.configuration.faye_url %>'});
  });
<% end %>
<div class="row">
  <div class="span8">
    <h3>Voting Booths</h3>
    <table id="booths">
      <thead>
        <tr>
          <th>#</th>
          <th>Status</th>
          <th>Active/Previous Voter</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @booths.each do |booth| %>
          <tr id="<%= dom_id(booth) %>">
            <td>
              <strong><%= booth.id %></strong>
            </td>
            <td>
              <span class="human_status label <%= booth.state.css_class %>"><%= booth.state.human_status %></span>
            </td>
            <td>
              <span class="voter_name"><%= booth.voter_name %></span>
            </td>
            <td>
              <%= button_to 'Connect', booth_connection_path(booth), class: 'btn', disable_with: 'Loading...', confirm: "You are about to logoff and reconnect this terminal as voting booth ##{booth.id}. Are you sure you wish to continue?" %>
              <%= button_to 'Reset', reset_booth_path(booth), class: 'btn', disable_with: 'Loading...', confirm: "You are about to reset this voting booth. If it has an active voter or ballot it will not be cast. Are you sure you wish to continue?" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="span8">
    <%= render 'voter_registration' %>
  </div>
</div>

app/views/layouts/_login_indicator.html.erb
<% if logged_in? %>
  <span class="login-indicator"><%= button_to('Logout', login_path, :method => 'delete') %></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glvote</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag Rails.configuration.faye_url + '.js' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    <%= yield(:javascript) %>
  </script>
</head>
  <body>
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <span class="brand">Grand Lodge Balloting 2012</span>
          <div class="pull-right">
            <% if @booth %>
              <span class="booth-indicator brand">Voting Booth #<%= @booth.id %></span>
            <% end %>
            <%= render 'layouts/login_indicator' %>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <% if flash.notice %>
        <div>
          <%= flash.notice %>
        </div>
      <% end %>
      <div class="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/booths.html.erb
<% content_for :javascript do %>
  $().ready(function() {
    window.booth_view = new GLVote.BoothView({faye_url: '<%= Rails.configuration.faye_url %>', booth_id: '<%= @booth.id %>', human_status: '<%= @booth.state.human_status %>', voter_name: '<%= @booth.voter_name %>'});
    $('form[data-remote]')
    .live('ajax:success', function(event, data, status, xhr) {
      $('.content').html(data);
    })
    .live('ajax:error', function(evt) {
    });
    $('.candidates input:radio').live('change', function() {
      $('.candidate').removeClass('success');
      $(this).parent().parent().addClass('success');
    });
  });
<% end %>
<%= render template: 'layouts/application' %>

app/views/login/new.html.erb
<%= form_for :login, url: login_path do |f| %>
  <fieldset>
    <legend>Login to activate this terminal</legend>
    <div class="clearfix">
      <%= f.label :password %>
      <div class="input">
        <%= f.password_field :password %>
        <%= f.submit 'Login', class: 'btn primary' %>
      </div>
    </div>
  </fieldset>
<% end %>